Panfrost: Fix build related to '-Znext-lockfile-bump'
Log:
error: failed to parse lock file at: /data1/khuongtrinh2/android_local_package-g3l-a17/mydroid/ninja-to-soong/Cargo.lock

Caused by:
  lock file version 4 requires `-Znext-lockfile-bump`

Signed-off-by: khuongtrinh2 <khuong.trinh.xg@renesas.com>